apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "canary"
    nginx.ingress.kubernetes.io/canary-by-header-value: "true"
spec:
  rules:
  - host: my-app.com
    http:
      paths:
      - path: /web
        backend:
          serviceName: svc-nginx2
          servicePort: 80
