env:
  open:
    DISABLE_API: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
  - name: chartmuseum.34.72.87.51.nip.io
    path: /
    tls: true
    tlsSecret: chartmuseum.34.72.87.51.nip.io
