expose:
  type: ingress
  tls:
    enabled: true
    secretName: "harbor-secret"
  ingress:
    hosts:
      core: harbor.34.72.87.51.nip.io
    controller: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
notary:
  enabled: false
