apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-server
        image: andel7/payment-service:v0.0.1
        env:
        - name: PORT
          value: "50051"

